name: Build and Push Docker Images
on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build and push Docker image for add-service
      run: |
        cd Addmodule
        docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/add-service:latest -f Dockerfile .
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/add-service:latest

    - name: Build and push Docker image for subtract-service
      run: |
        cd Submodule
        docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/subtract-service:latest -f Dockerfile .
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/subtract-service:latest

    - name: Build and push Docker image for divide-service
      run: |
        cd DivideModule
        docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/divide-service:latest -f Dockerfile .
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/divide-service:latest
