name: Build and Push Docker Image

on:
  workflow_dispatch:

jobs:
  build-docker-images:
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker images for add-service
      run: docker buildx build --platform linux/amd64,linux/arm64 -t $DOCKER_USERNAME/add-service:0.0.1 ./add-service

    - name: Push Docker images for add-service
      run: docker buildx imagetools create $DOCKER_USERNAME/add-service:0.0.1 | docker buildx imagetools push --platform linux/amd64,linux/arm64 --all -

    - name: Build Docker images for subtract-service
      run: docker buildx build --platform linux/amd64,linux/arm64 -t $DOCKER_USERNAME/subtract-service:0.0.1 ./subtract-service

    - name: Push Docker images for subtract-service
      run: docker buildx imagetools create $DOCKER_USERNAME/subtract-service:0.0.1 | docker buildx imagetools push --platform linux/amd64,linux/arm64 --all -

    - name: Build Docker images for gateway
      run: docker buildx build --platform linux/amd64,linux/arm64 -t $DOCKER_USERNAME/gateway:0.0.1 ./gateway

    - name: Push Docker images for gateway
      run: docker buildx imagetools create $DOCKER_USERNAME/gateway:0.0.1 | docker buildx imagetools push --platform linux/amd64,linux/arm64 --all -
