name: Build and Push Docker Image

on:
  workflow_dispatch:

jobs:
  build-docker-images:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build and push Docker images for add-service
      uses: docker/build-push-action@v2
      with:
        context: ./add-service
        file: ./add-service/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/add-service:0.0.1
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/add-service

    - name: Build and push Docker images for subtract-service
      uses: docker/build-push-action@v2
      with:
        context: ./subtract-service
        file: ./subtract-service/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/subtract-service:0.0.1
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/subtract-service

    - name: Build and push Docker images for gateway
      uses: docker/build-push-action@v2
      with:
        context: ./gateway
        file: ./gateway/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/gateway:0.0.1
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/gateway

