name: Build and Push Docker Images
on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Azure CLI
      uses: Azure/cli@v2
      with:
        azcliversion: latest

    - name: Login to Azure Container Registry
      run: az acr login --name ${{ secrets.ACR_REGISTRY }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push Docker image for add-service
      run: |
        cd Addmodule
        docker buildx create --use
        docker buildx build --platform linux/amd64,linux/arm64 -t ${{ secrets.ACR_REGISTRY }}/add-service:latest -f Dockerfile . --push

    - name: Build and push Docker image for subtract-service
      run: |
        cd Submodule
        docker buildx create --use
        docker buildx build --platform linux/amd64,linux/arm64 -t ${{ secrets.ACR_REGISTRY }}/subtract-service:latest -f Dockerfile . --push

    - name: Build and push Docker image for divide-service
      run: |
        cd DivideModule
        docker buildx create --use
        docker buildx build --platform linux/amd64,linux/arm64 -t ${{ secrets.ACR_REGISTRY }}/divide-service:latest -f Dockerfile . --push

    env:
      ACR_REGISTRY: ${{ secrets.ACR_REGISTRY }}
      ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
      ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
