name: Build and Push Docker Image

on:
  workflow_dispatch:

jobs:
  build-docker-images:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker images for add-service
      run: docker buildx build --platform linux/amd64,linux/arm64 -t ${{ secrets.DOCKER_USERNAME }}/add-service:0.0.1 --build-arg DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }} --build-arg DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }} ./add-service

    - name: Push Docker images for add-service
      run: docker buildx imagetools create ${{ secrets.DOCKER_USERNAME }}/add-service:0.0.1 | docker buildx imagetools push --platform linux/amd64,linux/arm64 --all -

    - name: Build Docker images for subtract-service
      run: docker buildx build --platform linux/amd64,linux/arm64 -t ${{ secrets.DOCKER_USERNAME }}/subtract-service:0.0.1 --build-arg DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }} --build-arg DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }} ./subtract-service

    - name: Push Docker images for subtract-service
      run: docker buildx imagetools create ${{ secrets.DOCKER_USERNAME }}/subtract-service:0.0.1 | docker buildx imagetools push --platform linux/amd64,linux/arm64 --all -

    - name: Build Docker images for gateway
      run: docker buildx build --platform linux/amd64,linux/arm64 -t ${{ secrets.DOCKER_USERNAME }}/gateway:0.0.1 --build-arg DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }} --build-arg DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }} ./gateway

    - name: Push Docker images for gateway
      run: docker buildx imagetools create ${{ secrets.DOCKER_USERNAME }}/gateway:0.0.1 | docker buildx imagetools push --platform linux/amd64,linux/arm64 --all -
